name: 'Deploy to gh-pages'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.20"
          cache: 'pnpm'

      - name: Install Node.js dependencies
        run: pnpm install

      - name: Build Project
        env:
          CI: false
        run: pnpm ui-deploy

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apps/ui/dist
